name: Heroku deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - ci-heroku

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 10
      # - run: yarn
      # - run: yarn test
      # - run: yarn build

      - run: echo "machine api.heroku.com login slavik.nychkalo@gmail.com password $HEROKU_API_KEY \nmachine git.heroku.com login slavik.nychkalo@gmail.com password $HEROKU_API_KEY" > ~/.netrc
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      - run: cat ~/.netrc
      - run: git remote add heroku https://git.heroku.com/audio-books-server.git
      - run: git push heroku HEAD:master